%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Uni_Stuttgart\Github\RENJulia\LipCNN\plots\FGSM_plot.csv
%
% Auto-generated by MATLAB on 18-Feb-2023 10:16:05

close all
clear all
clc

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 28);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
FGSMdata = readtable("D:\Uni_Stuttgart\Github\RENJulia\LipCNN\plots\FGSM_plot.csv", opts);

%% Convert to output type
FGSMdata = table2array(FGSMdata);

eps = FGSMdata(1,:);
FGSM_nom = FGSMdata(2,:);
FGSM_L2 = FGSMdata(3,:);
FGSM_Lip = FGSMdata(4,:);

%% Plot

figure('Position',[100,100,400,200])
plot(eps,FGSMdata(2:4,:)','linewidth',2)
xlabel('perturbation strength','interpreter','latex')
ylabel('test accuracy','interpreter','latex')
xlim([0,0.04])
legend('vanilla CNN', 'L2-reg. CNN', 'LipCNN','interpreter','latex')

matlab2tikz('plot_FGSM.tex')

